---

- hosts: all
  connection: local
  debugger: on_failed

  become: yes
  become_user: root

  pre_tasks:
    - name: Load local override variables
      include_vars:
        dir: vars
        ignore_files: [local-vars.default]
        extensions: [yml]

  roles:
