---

- hosts: localhost
  connection: local
  debugger: on_failed

  pre_tasks:
    - name: Load local override variables
      include_vars:
        dir: vars
        ignore_files: [local-vars.default]
        extensions: [yml]

  roles:
    - role: ansible-role.oh-my-zsh
